#!/usr/bin/env bash
# substitute index 4,9 and 17

j=1

while [ $j -le 20 ]
do
  echo "$j"
  case $j in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( j++ ))
done
